### ISSUE TITLE
Link given for #347

### ISSUE THREAD

**Issue by Kakarot-2000** [Birdy-C/DailyCodingProblem#3]
Hi @Birdy-C ,
I think that the link for #347 is different from the problem statement.
The difference is that the OG problem stmt requires appending the deleted character to the 'end of the string' (in any number of moves) whereas in the link provided the deleted character is appended to a new string of same size.
For eg : **Input : "xyzabc" should ideally give output "abcxyz"** for k=3 but the according to the algorithm of [https://www.geeksforgeeks.org/lexicographically-smallest-string-formed-by-appending-a-character-from-the-first-k-characters-of-a-given-string/](url)  it gives "xabcyz"

**Comment by Birdy-C** [comment]
Yeah, you are right. Do you find a better solution / wanna write a post for it? : )

**Comment by Kakarot-2000** [comment]
Yes Definitely. I did find an O(n) time solution for this. I've posted my solution here https://kakarot2000.medium.com/lexicographically-smallest-string-that-can-be-created-after-an-unlimited-number-of-moves-e5d941783ab1

**Comment by Birdy-C** [comment]
1. Sort is O(nlogn)
2. I'm lost here, may I ask how to get the result for "abdc" with k = 2?

**Comment by Birdy-C** [comment]
> 1. Sort is O(nlogn)
> 2. I'm lost here, may I ask how to get the result for "abdc" with k = 2?

“abdc” -> "dcab" -> "abcd" got it. I'll put it into the repo.

**Comment by Kakarot-2000** [comment]
Yeah the time complexity is O(nlogn) not O(n) sorry😅.
For input "abdc" k=2, we can take either of the first 2 characters 'a' and 'b' in step1.
1. abdc-->bdc(after deleting a)-->bdca(after adding a at the end)
2. bdca-->dca(after deleting b)-->dcab(after adding b at the end)
3. dcab-->dab(after deleting c)-->dabc(after adding c at the end)
4. dabc-->abc(after deleting d)-->abcd (after adding d at the end)
So, whenever k>1 we can finally get the result as lexicographically smallest string possible from all characters in the input string.
I hope cleared your query 😄

**Comment by Kakarot-2000** [comment]
> > 1. Sort is O(nlogn)
> > 2. I'm lost here, may I ask how to get the result for "abdc" with k = 2?
> 
> “abdc” -> "dcab" -> "abcd" got it. I'll put it into the repo.

Thankyou 😄

**Comment by Birdy-C** [comment]
Thanks!!

**Comment by Birdy-C** [comment]
I gonna close this issue, feel free to ask any question :) I didn't look into all the questions closely and quite possible to make mistakes.
